services:
  postgres:
    image: docker.io/library/postgres:15.4
    container_name: postgres
    volumes: 
    - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=molly_master
      - TZ=Asia/Taipei
    ports:
      - "5432:5432" 
volumes: 
  postgres-data: { }