### 獲取全部使用者
GET {{baseUrl}}/people
Content-Type: application/json
x-tenant-id: MSFT


### 新增 用戶
POST {{baseUrl}}/people
Content-Type: application/json
x-tenant-id: MSFT

{
  "name": "比爾·蓋茨",
  "age": 67,
  "grade": [1,2,3],
  "hobby": ["籃球","泡澡","桑拿"]
}


### 新增 用戶 2
POST {{baseUrl}}/people
Content-Type: application/json
x-tenant-id: GOOG

{
  "name": "拉裡·佩奇",
  "age": 49,
  "grade": [4,5,6],
  "hobby": ["唱K","跳舞","拳擊"]
}



### 獲取全部租戶
GET {{baseUrl}}/tenant
Content-Type: application/json
x-tenant-id: master


### 新增租戶
POST {{baseUrl}}/tenant
Content-Type: application/json
x-tenant-id: master

{
  "tenantId": "MSFT",
  "name": "microsoft"
}
